# Generated by Django 4.0.6 on 2022-10-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qauntity',
            new_name='quantity',
        ),
    ]
